# Aurora uses Timeshift snapshots; enabled by the installer on btrfs only.
[Unit]
ConditionPathExists=/etc/timeshift/timeshift.json

[Service]
ExecStart=
ExecStart=/usr/bin/grub-btrfsd --syslog --timeshift-auto
