---
backend: apt
skip_if_no_internet: false
update_db: false
operations:
  - remove:
      - 'live-boot'
      - 'live-boot-doc'
      - 'live-boot-initramfs-tools'
      - 'live-tools'
      - 'calamares-settings-debian'
      - 'calamares'
