---
efi:
    mountPoint: "/boot/efi"
    recommendedSize: 512MiB
    minimumSize: 300MiB
    label: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file
initialSwapChoice: file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
showNotEncryptedBootMessage: true
initialPartitioningChoice: erase

defaultFileSystemType: "btrfs"
availableFileSystemTypes: ["btrfs", "ext4", "xfs"]

enableLuksAutomatedPartitioning: true
luksGeneration: luks2

partitionLayout:
    - name: "aurora"
      filesystem: "unknown"
      mountPoint: "/"
      size: 100%
