---
units:
  - name: "aurora-live-setup.service"
    action: "disable"
  - name: "greetd.service"
    action: "enable"
  - name: "NetworkManager.service"
    action: "enable"
  - name: "ufw.service"
    action: "enable"
    mandatory: false
