---
userGroup: users
defaultGroups:
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - render
    - input
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth
    - docker
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: true
allowWeakPasswords: true
allowWeakPasswordsDefault: false
passwordRequirements:
    nonempty: true
    minLength: 4
    maxLength: -1
    libpwquality:
        - minlen=4
        - minclass=0
user:
  shell: /bin/bash
  forbidden_names: [ root, aurora ]
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "aurora-${cpu}"
  forbidden_names: [ localhost ]
